#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated by ChatGPT 5.2
"""Insert a newline after Chinese punctuation marks.

Reads text character-by-character. When encountering '！'、'？'、'。',
adds a newline immediately after it.

By default writes to stdout. Use -o to write to a file, or --in-place to
modify the input file.

Examples:
  python wrap_chinese_punct_newlines.py input.txt -o output.txt
  python wrap_chinese_punct_newlines.py input.txt --in-place
  type input.txt | python wrap_chinese_punct_newlines.py -
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import TextIO, cast


PUNCTUATIONS = {"！", "？", "。"}
NEWLINE_CHARS = {"\n", "\r"}


def _open_text(path: str, mode: str) -> TextIO:
    # newline='' preserves \r / \n exactly as in the file.
    return cast(TextIO, open(path, mode, encoding="utf-8", newline=""))


def transform_stream(reader: TextIO, writer: TextIO) -> None:
    """Transform by inserting '\n' after target punctuation."""

    buffered: str | None = None

    while True:
        ch = buffered if buffered is not None else reader.read(1)
        buffered = None

        if ch == "":
            return

        if ch in PUNCTUATIONS:
            writer.write(ch)

            # Look ahead one char to avoid inserting an extra newline
            # if the next char is already a newline (\n or \r\n).
            nxt = reader.read(1)
            if nxt == "":
                writer.write("\n")
                return

            if nxt in NEWLINE_CHARS:
                writer.write(nxt)
                if nxt == "\r":
                    nxt2 = reader.read(1)
                    if nxt2 == "\n":
                        writer.write(nxt2)
                    elif nxt2 != "":
                        buffered = nxt2
                continue

            writer.write("\n")
            buffered = nxt
            continue

        writer.write(ch)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Insert newline after '！' '？' '。'.")
    parser.add_argument(
        "input",
        help="Input file path, or '-' to read from stdin.",
    )
    parser.add_argument(
        "-o",
        "--output",
        help="Output file path. If omitted, writes to stdout (unless --in-place).",
    )
    parser.add_argument(
        "--in-place",
        action="store_true",
        help="Modify the input file in place (cannot be used with '-' input).",
    )

    args = parser.parse_args(argv)

    if args.in_place and args.input == "-":
        parser.error("--in-place cannot be used when input is '-' (stdin).")

    if args.in_place and args.output:
        parser.error("--in-place and --output cannot be used together.")

    if args.input == "-":
        reader = sys.stdin
    else:
        reader = _open_text(args.input, "r")

    try:
        if args.in_place:
            tmp_path = f"{args.input}.tmp"
            with _open_text(tmp_path, "w") as writer:
                transform_stream(reader, writer)

            if reader is not sys.stdin:
                reader.close()

            os.replace(tmp_path, args.input)
            return 0

        if args.output:
            with _open_text(args.output, "w") as writer:
                transform_stream(reader, writer)
            return 0

        transform_stream(reader, sys.stdout)
        return 0
    finally:
        if reader is not sys.stdin:
            reader.close()


if __name__ == "__main__":
    raise SystemExit(main())
